adata_path:
<<<<<<< HEAD
  - /home/labs/nyosef/yoavnah/CellRangerIDE/Projects/giaco/OutputFiles/Liver_1/outs/multi/count/raw_feature_bc_matrix.h5

sample_names:
  - Liver_1

hto_list_per_sample: # Pay attention that the lenght of the list compatible to the sample_name list
  - ['IKK_RORc_Ko_m1_median_lobe', 'IKK_RORc_KO_m1_left_lobe', 'IKK_RORc_KO_m2_median_lobe', 'IKK_RORc_KO_m2_left_lobe']
=======
  - /home/labs/nyosef/Collaboration/Liver/Liver_3/outs/multi/count/raw_feature_bc_matrix.h5

sample_names:
  - Liver_3

hto_list_per_sample: # Pay attention that the lenght of the list compatible to the sample_name list
  - ['IKK_m3_hilar_lymph_nodes', 'IKK_m4_hilar_lymph_nodes']
>>>>>>> argparser

demultiplex_method: demultiplex2 # hashsolo or demultiplex2

# Default: [negative probabiltity = 0.01, singlet probability = 0.8, doublet probability = 0.19]
# For hashsolo only
priors:     # Pay attention that the lenght of the list compatible to the sample_name list
  - [0.85,0.12,0.03]

  