# This is the configuration file to run the cellranger pipeline which creates annotated data files for one sample!


# Required
id: 
   - 
   -

# Default: refdata-gex-mm10-2020-A
alignment_ref_genome_file:

# Required
fastq_path:
   -
   -
