# This is the configuration file to run the cellranger pipeline which creates annotated data files for one sample!


# Required
<<<<<<< HEAD
id: 
   - 
   -
=======
sample_name:
>>>>>>> argparser

# Default: refdata-gex-mm10-2020-A
alignment_ref_genome_file:

# Required
<<<<<<< HEAD
fastq_path:
   -
   -
=======
fastq_path:
>>>>>>> argparser
